library/hashlib.rst:742: [broken] https://cr.yp.to/chacha.html: HTTPSConnectionPool(host='cr.yp.to', port=443): Max retries exceeded with url: /chacha.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4dd1113550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
library/mailbox.rst:434: [broken] https://cr.yp.to/proto/maildir.html: HTTPSConnectionPool(host='cr.yp.to', port=443): Max retries exceeded with url: /proto/maildir.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4dd10956d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
whatsnew/2.7.rst:1203: [broken] https://bugs.python.org/issue?@action=redirect&bpo=6595: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/50844
whatsnew/2.7.rst:1514: [broken] https://bugs.python.org/issue?@action=redirect&bpo=8104: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/52351
whatsnew/3.3.rst:1541: [broken] https://bugs.python.org/issue?@action=redirect&bpo=6064: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/50314
whatsnew/3.4.rst:1460: [broken] https://bugs.python.org/issue?@action=redirect&bpo=8813: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/53059
whatsnew/changelog.rst:14228: [broken] https://bugs.python.org/issue?@action=redirect&bpo=40328: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/84508
whatsnew/changelog.rst:14723: [broken] https://bugs.python.org/issue?@action=redirect&bpo=40091: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/84272
whatsnew/changelog.rst:36302: [broken] https://bugs.python.org/issue?@action=redirect&bpo=9858: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/54067
whatsnew/changelog.rst:5042: [broken] https://bugs.python.org/issue?@action=redirect&bpo=46681: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/90839
whatsnew/changelog.rst:6637: [broken] https://bugs.python.org/issue?@action=redirect&bpo=46576: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/90734
whatsnew/changelog.rst:695: [broken] https://github.com/python/cpython/issues/88233: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/88233
whatsnew/changelog.rst:7843: [broken] https://bugs.python.org/issue?@action=redirect&bpo=45417: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/89580
whatsnew/changelog.rst:7971: [broken] https://bugs.python.org/issue?@action=redirect&bpo=45449: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/89612
whatsnew/changelog.rst:9620: [broken] https://bugs.python.org/issue?@action=redirect&bpo=40620: 500 Server Error: Internal Server Error for url: https://github.com/python/cpython/issues/84800
